### ISSUE TITLE
Clarify / change description - handwritten parser, not parser for handwritten math

### ISSUE THREAD

**Issue by ChrisDavison** [gnebehay/parser#2]
Found this on HackerNews under the description *"A Handwritten Math Parser in 100 lines of Python (github.com)"*, which led me to believe that this was a parser for _handwritten math_ (i.e. you write on paper, and it can detect the equation).

It may be beneficial for others if the repo description and readme were reworded to clarify that 'handwritten' here applies to the fact you wrote the code yourself, and not to the type of math that can be parsed.

**Comment by gnebehay** [comment]
Thanks for the feedback!
