### ISSUE TITLE
Computes "7-4+2" as 1, not 5

### ISSUE THREAD

**Issue by AZHenley** [gnebehay/parser#3]
The parser treats all operators as right associative so that "7-4+2" is treated as 7-(4+2) and evaluates to 1 instead of 5.

**Comment by gnebehay** [comment]
Thanks for spotting this, will look into it!

**Comment by gnebehay** [comment]
Added this as a known issue to the Readme, will try to investigate more how to solve this, but currently it looks like a surprising limitation of LL(1) parsers that you cannot have left-associativity. https://cs.stackexchange.com/a/43071

**Comment by AZHenley** [comment]
The typical solution is to write the grammar to allow repetition for each rule:

`expression ::= term {( "-" | "+" ) term}
term ::= unary {( "/" | "*" ) unary}
unary ::= ["+" | "-"] primary`

**Comment by gnebehay** [comment]
ah, that makes sense, will give it a try!
